firstProject/firstProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('minichat/', include("minichat.urls")),
    path('encyclopedia/', include("encyclopedia.urls")),
    path('flights/', include("flights.urls")),
    path('sale/', include("sale.urls")),
  
]

firstProject/sale/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:customer_id>', views.customer, name="customer"),
    path('order/', views.order, name="order"),
    path('purchase/<int:customer_id>', views.order, name="order"),
   
]

firstProject/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
]

firstProject/tasks/models.py
from django.db import models

# Create your models here.

firstProject/tasks/views.py
from django.shortcuts import render
from django import forms 

class NewTaskForm(forms.Form):
    add = forms.CharField(label="Add a task:", max_length=15)

tasks = ["kitchen", "Dishes", "Laundry", "Swipping"]

def index(request):
    return render(request, "tasks/index.html", {
        "task": tasks
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            add = form.cleaned_data["add"]
            tasks.append(add)
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

firstProject/tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block title %}Add task{% endblock title %}

{% block body %}

    <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        <ul>
            {{form}}
        </ul>
        <br /><br />
        <input type="submit" value="Submit task" name="newtask" />
    </form>
    <br /><br />


    <a href="{% url 'tasks:index' %}"> View tasks </a>
{% endblock body %}

firstProject/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block title %}Task list{% endblock title %}

{% block body %}
    <ul>
        {% for i in task %}
        <li> {{i}}</li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'tasks:add'%}" title="clic to add a task">Click here</a> 
        to add a task</p>
{% endblock body %}

firstProject/tasks/templates/tasks/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'tasks/style.css' %}" />
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block body %}
    
    {% endblock body %}
</body>
</html>