firstProject/encyclopedia/urls.py
from django.urls import path
from . import views


app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.title, name="title"),
    path("newEntry/", views.newEntry, name="newEntry"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random/", views.random, name="random"),
]

firstProject/firstProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('minichat/', include("minichat.urls")),
    path('encyclopedia/', include("encyclopedia.urls")),
    path('flights/', include("flights.urls")),
    path('sale/', include("sale.urls")),
  
]

firstProject/sale/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:customer_id>', views.customer, name="customer"),
    path('order/', views.order, name="order"),
    path('purchase/<int:customer_id>', views.order, name="order"),
   
]

firstProject/encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
import random
from . import util



class NewEntryWiki(forms.Form):
    title = forms.CharField(label="Title ", max_length=50)
    text = forms.CharField(label="", widget=forms.Textarea(attrs={"cols":60, "rows": 15}), initial="moi")

class Edit(forms.Form):
    forms.CharField(label="", widget=forms.Textarea(attrs={"cols":60, "rows": 15}),
    initial="")

formular = NewEntryWiki()
content = ""

def index(request):
    return render(request, "encyclopedia/index.html", {
        "list": util.list_entries()
    })

def title(request, title):
    return render(request, "encyclopedia/title.html",{
        "title_entry": title,
        "title_found": util.get_entry(title)
        
    })

def newEntry(request):
    if request.method == "POST":
        form = NewEntryWiki(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            text = form.cleaned_data["text"]
            util.save_entry(title, text)
            return HttpResponseRedirect(reverse('encyclopedia:index'))
            
        else:
            return render(request, "encyclopedia/newEntry.html",{
                "form": form
            })
    
    return render(request, "encyclopedia/newEntry.html", {
        "form": formular.as_p()
    })

def edit(request, title):
    if request.method == "POST":
        update = request.POST.get("edit")
        if update:
            util.save_entry(title, update) 
            return HttpResponseRedirect(f"../{title}")
            
        else:
            return render(request, "encyclopedia/edit.html")
    return render(request, "encyclopedia/edit.html", {
        "content": util.get_entry(title),
        "title": title
    
    })

def random(request):
    content = len(util.list_entries())
    content = content * random.randint()
    return render(request, "encyclopedia/random.html", {
        "content": content
    })

firstProject/encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}    

{% block title %}Edition page {% endblock title %}

{% block body %}
    <h3>Edit this content </h3><br /><br />
    <form action="#" method="POST">
        {% csrf_token %}
        <textarea cols="60" rows="15" name="edit">
            {{content}}
        </textarea><br /><br />
        <input type="submit" value="Update content" />
    </form>
{% endblock body %}

firstProject/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in list %}
            <h3><a href='{{entry}}'> {{ entry }} </a></h3>
        {% endfor %}
    </ul>

{% endblock %}

firstProject/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newEntry' %}"> Create New Page </a>
                </div>
                <div>
                    <a href=" {% url 'encyclopedia:random' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

firstProject/encyclopedia/templates/encyclopedia/newEntry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}New entry{% endblock title %}

{% block body %}

    <h2>Save a new Entry</h2><br />
    <section>
        <form action='#' method="POST">
            {% csrf_token %}
            {{form}}<br />

            <input type="submit" value="Save entry" />
        </form>
    </section>
{% endblock body %}

firstProject/encyclopedia/templates/encyclopedia/random.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Random entry{% endblock title %}

{% block body %}

    {{content}}

{% endblock body %}

firstProject/encyclopedia/templates/encyclopedia/title.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Looking for-{{title_entry}}
{% endblock title %}

{% block body %}
    <h2>Result for "{{title_entry}}"</h2>
    {% if title_found == None %}
        No result has been found for "{{title_entry}}"
    {% else %}
         <p>
           {{title_found}}<br /><br />
                
                <a href="edit/{{title_entry}}" />Edit this content</a>
        </p>
    {% endif %}
   

{% endblock body %}